
name: Build

on:
  push:
    branches: 
    - '**' 

  workflow_dispatch:

jobs:


  build-win32:
    
    runs-on: windows-2019
    steps:
          
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild and add to PATH
      id: setup_msbuild
      uses: microsoft/setup-msbuild@v1.0.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Run MSBuild
      id: run_msbuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ./project/gba-demo.vcxproj /p:configuration=release /p:platform=win32
      
    - uses: actions/upload-artifact@v2
      with:
        name: gba-demo-win32
        path: ./build/out/Release/gba-demo.exe


  build-gba:
    
    runs-on: ubuntu-20.04
    steps:
          
    - uses: actions/checkout@v2
      
    - uses: ./.github/workflows/devkitarm-docker-action

    - run: mv workspace.gba gba-demo.gba

    - uses: actions/upload-artifact@v2
      with:
        name: gba-demo
        path: ./gba-demo.gba


  test-gba:
    
    needs: build-gba
    
    runs-on: windows-2019
    steps:
          
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild and add to PATH
      id: setup_msbuild
      uses: microsoft/setup-msbuild@v1.0.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        
    - name: nuget setup
      id: setup_nuget
      uses: nuget/setup-nuget@v1
      
    - name: nuget restore
      id: restore_nuget
      run: nuget restore ./tests/gba-test.csproj
      
    - name: Run MSBuild
      id: run_msbuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ./tests/gba-test.csproj /p:configuration=release /p:platform=win32
      
    - name: download built gba rom
      id: download_artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: gba-demo
        path: ./gba-demo.gba

    - name: Install NUnit
      id: install_nunit
      run: nuget install NUnit.Console -Version 3.12.0
      
    - run: dir 
        
    - name: Run Tests
      id: run_tests
      run: ./NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./tests/bin/win32/release/netcoreapp3.1/gba-test.dll --params:rom=./gba-demo.gba

   
